In [1]:
import json
import h5py
from load_data import *
from model import *
from plotting import *
import tensorflow as tf 
import os
from numpy import sqrt as sqrt

Importamos los ground truth del conjunto de entrenamiento y test. 

In [62]:
json_train = open('JSON FILES\DTS_SG_part_A.json')
json_test = open('JSON FILES\DTS_SG_part_A_TEST.json')
paths_train = json.load(json_train)
paths_test = json.load(json_test)

#Cargamos la data 
train_GT = mLoad_GT(paths_train, 5)
train_img = mLoad_Img(paths_train, 5)

test_GT = mLoad_GT(paths_test, 5)
test_img = mLoad_Img(paths_test, 5)

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf 
import pandas as pd


def count_estimate_GC(test_img, test_gt, predict, name):
    N = len(test_gt)
    resume = pd.DataFrame({'GT':[], 'Pred':[]})
    
    for i in range(N):
        IMG = test_img[i,:,:,0]
        GT = test_gt[i,:,:,0]
        PRED = predict[i,:,:,0]
        
        est_count = tf.math.reduce_sum(PRED)
        GT_count = tf.math.reduce_sum(GT)
        
        resume.loc[i, 'GT'] = GT_count
        resume.loc[i, 'Pred'] = est_count
    
    resume.to_excel(name + '.xlsx')

In [71]:
train = tf.data.Dataset.from_tensor_slices((train_img, train_GT)).batch(50)

test = tf.data.Dataset.from_tensor_slices((test_img, test_GT))




In [73]:
for batch in train:
    print(batch[0])

tf.Tensor(
[[[[0.9971945 ]
   [0.9826392 ]
   [0.98627806]
   ...
   [0.92578787]
   [0.92970943]
   [0.9330655 ]]

  [[0.98627806]
   [0.98991686]
   [0.9787176 ]
   ...
   [0.95323884]
   [0.90618   ]
   [0.8663988 ]]

  [[0.9787176 ]
   [0.9971945 ]
   [0.9971945 ]
   ...
   [0.87872905]
   [0.8865722 ]
   [0.9056145 ]]

  ...

  [[0.73823726]
   [0.7303941 ]
   [0.722551  ]
   ...
   [0.72330785]
   [0.7193863 ]
   [0.7154647 ]]

  [[0.72647256]
   [0.7186294 ]
   [0.71245295]
   ...
   [0.7389941 ]
   [0.73507255]
   [0.731151  ]]

  [[0.7163745 ]
   [0.71245295]
   [0.70068824]
   ...
   [0.7507588 ]
   [0.74683726]
   [0.7429157 ]]]


 [[[0.        ]
   [0.        ]
   [0.        ]
   ...
   [0.        ]
   [0.        ]
   [0.        ]]

  [[0.        ]
   [0.        ]
   [0.        ]
   ...
   [0.        ]
   [0.        ]
   [0.        ]]

  [[0.        ]
   [0.        ]
   [0.        ]
   ...
   [0.        ]
   [0.        ]
   [0.        ]]

  ...

  [[0.        ]
   [0.      

In [3]:
f = h5py.File(r'C:\Users\Usuario\Documents\Nueva carpeta\Gaussian-Derivates-Network\training\resume.h5', 'r')

In [4]:
predict = np.asarray(f['predict'])

Construimos la red neuronal. Este sera un prototipo hasta siguiente cambio

Entrenamos un poco para testeo!

In [ ]:
pre_trained = r"training\cp-0050.ckpt"
model.load_weights(pre_trained)

In [6]:
count_estimate(test_img, test_GT, predict, model)